theme: jekyll-theme-cayman
title: Kunal's webpage
description: Short Bio: I am presently working as a Data scientist wherein I build and deploy machine learning based solutions to interesting problems. My work has centered around problems in 
online-advertising, marketing or operational forecasting. Previously, I obtained a PhD in Mathematics. Specifically, I worked on Index theory(out of Atiyah-Singer Index theorem)
which, briefly speaking, explores the interplay between analysis and topology. In addition, I have also worked in Riemannian geometry and smooth dynamical systems. In essence, I 
have a strong interest in problem involving rich geometry. In machine learning, its fascinating to see that in areas of Topological data analysis, Geometric deep learning(Graph Convolution Networks, manifold learning) and 
and Knowledge graphs. 
